[book]
authors = ["Daniel Xu"]
language = "en"
multilingual = false
src = "src"
title = "prr"

[output.html]
git-repository-url = "https://github.com/danobi/prr"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/danobi/prr/edit/master/book/{path}"
